import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { MSWProvider } from './_component/MSWComponent';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

// todo : 서버컴포넌트이면서 개발서버 일 때
if (
  process.env.NEXT_RUNTIME === 'nodejs' &&
  process.env.NODE_ENV !== 'production'
) {
  const { server } = require('@/mocks/http');
  server.listen();
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: React.ReactNode;
};
export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MSWProvider>{children}</MSWProvider>
      </body>
    </html>
  );
}
